### ISSUE TITLE
Custom Dataset Training

### ISSUE THREAD

**Issue by abhisheksurya578** [danbochman/Real-Time-Action-Recognition#2]
Hi @danbochman 

Can we train it on Custom Video Data set with 8 classes.

Please help me..

**Comment by lws803** [comment]
I second that, are there any possibilities of transfer learning for this model?

**Comment by danbochman** [comment]
Hello @abhisheksurya578  and @lws803,
Sorry for the late reply, yes! you can train it on another dataset, and also use it as a base for transfer learning. It will require some modifications to the code but not alot! All you have to do is modify the dataloader/XXX_dataloader.py to grab the files from your dataset, instead of that of the UCF-101.
The data for the motion_dataloader.py will be a bit trickier, you will have to pre-process your data and create your own optical flow images using some FlowNet (recommended) implementation. Once you have your optical flow data, you can modify this script to load it just like it's being done right now. 
Let me know if I can be of further assistance!
